# Generated by Django 3.2.7 on 2021-09-08 17:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nohp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
            preserve_default=False,
        ),
    ]
