# Generated by Django 3.2.7 on 2021-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='status',
            field=models.CharField(default='Not Activated', max_length=25),
        ),
    ]
